### ISSUE TITLE
Duplicate information

### ISSUE THREAD

**Issue by XXY233** [voruti/VelocityPlayerListQuery#52]
It looks like the Minecraft client automatically handles remaining players, is it possible to provide an option to hide the plugin's "and x more" message?

![image](https://github.com/user-attachments/assets/e11d8919-91c0-4964-9612-1c464e4c619e)

config file:
```
{
  "playerListMode": "REPLACE",
  "serverListEntryFormat": "%1$s",
  "maxListEntries": 6,
  "replaceOnlinePlayerCount": false,
  "replaceMaxPlayerCount": false,
  "fillMissingVersionInfo": false,
  "replaceVersionInfo": false,
  "versionProtocol": 4,
  "versionName": "Velocity"
}
```

**Comment by XXY233** [comment]
If I set maxListEntries to -1 then the list can get too long, the vanilla client doesn't seem to limit the list length for the sample player.

**Comment by voruti** [comment]
I see...
